-- ARTHA V0 schema
-- Design notes:
--  * All primary keys are TEXT UUIDs (v4) generated by the application, so
--    purchase/sale/audit records stay stable and mergeable across backups,
--    exports and (future) multi-location sync.
--  * Money and quantity are stored as INTEGER (paise / smallest unit, and
--    thousandths of a unit respectively) to avoid floating point drift.
--  * `created_at` / `updated_at` are ISO-8601 UTC strings (TEXT), written by
--    the application so tests can control time.
--  * Foreign keys are enforced; the app turns on `PRAGMA foreign_keys = ON`
--    and `PRAGMA journal_mode = WAL` on every connection.

CREATE TABLE IF NOT EXISTS businesses (
    business_id   TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    settings_json TEXT NOT NULL DEFAULT '{}',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

-- Only one row is expected in V0 (single-business, single-owner-PC), but the
-- column exists everywhere now so a future multi-business mode (V3) needs no
-- schema migration on the hot tables.
CREATE TABLE IF NOT EXISTS users (
    user_id        TEXT PRIMARY KEY,
    business_id    TEXT NOT NULL REFERENCES businesses(business_id),
    username       TEXT NOT NULL,
    password_hash  TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('owner', 'staff')),
    status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    UNIQUE (business_id, username)
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id   TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(user_id),
    token_hash   TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    revoked_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS products (
    product_id    TEXT PRIMARY KEY,
    business_id   TEXT NOT NULL REFERENCES businesses(business_id),
    name          TEXT NOT NULL,
    batch         TEXT,
    hsn_code      TEXT,
    gst_rate_bps  INTEGER NOT NULL DEFAULT 0, -- basis points, e.g. 1800 = 18.00%
    qr_code       TEXT NOT NULL,
    price_paise   INTEGER NOT NULL DEFAULT 0,
    cost_paise    INTEGER NOT NULL DEFAULT 0,
    stock_qty_milli INTEGER NOT NULL DEFAULT 0, -- thousandths of a unit
    unit          TEXT NOT NULL DEFAULT 'pcs',
    status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    UNIQUE (business_id, qr_code)
);

CREATE INDEX IF NOT EXISTS idx_products_business ON products(business_id);
CREATE INDEX IF NOT EXISTS idx_products_qr ON products(business_id, qr_code);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id   TEXT PRIMARY KEY,
    business_id   TEXT NOT NULL REFERENCES businesses(business_id),
    name          TEXT NOT NULL,
    contact       TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS purchases (
    purchase_id   TEXT PRIMARY KEY,
    business_id   TEXT NOT NULL REFERENCES businesses(business_id),
    supplier_id   TEXT REFERENCES suppliers(supplier_id),
    invoice_no    TEXT,
    invoice_date  TEXT,
    status        TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'void')),
    total_paise   INTEGER NOT NULL DEFAULT 0,
    created_by    TEXT NOT NULL REFERENCES users(user_id),
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    approved_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_purchases_business ON purchases(business_id);

CREATE TABLE IF NOT EXISTS purchase_items (
    purchase_item_id TEXT PRIMARY KEY,
    purchase_id      TEXT NOT NULL REFERENCES purchases(purchase_id),
    product_id       TEXT NOT NULL REFERENCES products(product_id),
    batch            TEXT,
    hsn_code         TEXT,
    gst_rate_bps     INTEGER NOT NULL DEFAULT 0,
    quantity_milli   INTEGER NOT NULL,
    price_paise      INTEGER NOT NULL,
    line_total_paise INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase ON purchase_items(purchase_id);

CREATE TABLE IF NOT EXISTS sales (
    sale_id       TEXT PRIMARY KEY,
    business_id   TEXT NOT NULL REFERENCES businesses(business_id),
    customer_name TEXT,
    invoice_no    TEXT,
    status        TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'void')),
    total_paise   INTEGER NOT NULL DEFAULT 0,
    created_by    TEXT NOT NULL REFERENCES users(user_id),
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    approved_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_sales_business ON sales(business_id);

CREATE TABLE IF NOT EXISTS sale_items (
    sale_item_id     TEXT PRIMARY KEY,
    sale_id          TEXT NOT NULL REFERENCES sales(sale_id),
    product_id       TEXT NOT NULL REFERENCES products(product_id),
    quantity_milli   INTEGER NOT NULL,
    rate_paise       INTEGER NOT NULL,
    discount_paise   INTEGER NOT NULL DEFAULT 0,
    gst_rate_bps     INTEGER NOT NULL DEFAULT 0,
    line_total_paise INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);

CREATE TABLE IF NOT EXISTS bill_images (
    image_id     TEXT PRIMARY KEY,
    purchase_id  TEXT REFERENCES purchases(purchase_id),
    path         TEXT NOT NULL,
    sha256_hex   TEXT NOT NULL,
    created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ocr_results (
    ocr_id        TEXT PRIMARY KEY,
    image_id      TEXT NOT NULL REFERENCES bill_images(image_id),
    text_json     TEXT NOT NULL,   -- raw OCR text blocks
    boxes_json    TEXT NOT NULL,   -- bounding boxes
    confidence    REAL NOT NULL,
    engine_version TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS backups (
    backup_id      TEXT PRIMARY KEY,
    app_version    TEXT NOT NULL,
    schema_version INTEGER NOT NULL,
    path           TEXT NOT NULL,
    checksum_sha256 TEXT NOT NULL,
    created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_versions (
    version       TEXT PRIMARY KEY,
    package_hash  TEXT NOT NULL,
    kind          TEXT NOT NULL CHECK (kind IN ('app', 'ocr_model')),
    released_at   TEXT NOT NULL,
    notes         TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_id     TEXT PRIMARY KEY,
    business_id  TEXT NOT NULL REFERENCES businesses(business_id),
    user_id      TEXT REFERENCES users(user_id),
    action       TEXT NOT NULL,
    entity_type  TEXT NOT NULL,
    entity_id    TEXT,
    detail_json  TEXT NOT NULL DEFAULT '{}',
    created_at   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_business ON audit_log(business_id, created_at);
